//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEFURUnbilled
    {
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string TicketingAgent { get; set; }
        public decimal InvoiceID { get; set; }
        public Nullable<decimal> InvoiceDetailID { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string VendorNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public string TicketNumber { get; set; }
        public Nullable<byte> TransactionType { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string ProfileName { get; set; }
        public string BookingAgentNumber { get; set; }
        public string PassengerName { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public string RecordLocator { get; set; }
        public string FullName { get; set; }
        public string FreeFieldA { get; set; }
        public string Department { get; set; }
        public string TicketingAgentNumber { get; set; }
    }
}
