//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEFURUnbilledCount
    {
        public Nullable<int> UnbilledCount { get; set; }
        public string BookingAgent { get; set; }
        public long id { get; set; }
    }
}
