//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObizAccountingInvoiceCount
    {
        public string RecordLocator { get; set; }
        public string ProfileName { get; set; }
        public decimal AddedBy { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string Login { get; set; }
    }
}
