//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesReport
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<System.Guid> ClientID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string TypeOfActivity { get; set; }
        public string AgendaIssueConcerns { get; set; }
        public string ScopeAction { get; set; }
        public string CompanyUpdate { get; set; }
        public string Remarks { get; set; }
        public string BCDDeliverables { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Status { get; set; }
        public string Category { get; set; }
        public string SLA { get; set; }
    }
}
