//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public System.Guid ID { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public string Department { get; set; }
        public string Password { get; set; }
        public string Status { get; set; }
        public string AgentCode1 { get; set; }
        public string AgentCode2 { get; set; }
        public string AgentCode3 { get; set; }
        public string PartnerAgent { get; set; }
        public string CebBizPartner { get; set; }
        public string DepartmentHead { get; set; }
        public string Email { get; set; }
        public string ClientMagicLogin { get; set; }
        public string Type { get; set; }
    }
}
